In [ ]:
#Q1
import numpy as np

arr = np.array([10,20,30,40,50])

#a)
addition = arr + 2
print("addition:" , addition)

#b)
multiply = arr*3
print("multiplication: ", multiply)

#c)
divide = arr/2
print("division: ",divide)


addition: [12 22 32 42 52]
multiplication:  [ 30  60  90 120 150]
division:  [ 5. 10. 15. 20. 25.]


In [ ]:
#Q2
import numpy as np
#a)
arr = np.array([1,2,3,6,4,5])

rev = arr[::-1]
print("Original array:", arr)
print("Reversed array: ",rev)

#b)
x= np.array([1,2,3,4,5,1,2,1,1,1])
values,counts = np.unique(x,return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x==most_frequent)[0]
print("Most frequent value:" ,most_frequent)
print("indices: ", indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values,counts = np.unique(y,return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y==most_frequent)[0]
print("Most frequent value:" ,most_frequent)
print("indices: ", indices)

Original array: [1 2 3 6 4 5]
Reversed array:  [5 4 6 3 2 1]
Most frequent value: 1
indices:  [0 5 7 8 9]
Most frequent value: 1
indices:  [0 1 2]


In [ ]:
#Q3
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("1st row, 2nd column", arr[0,1])
print("3rd row, 1st column", arr[2,0])

1st row, 2nd column 20
3rd row, 1st column 70


In [ ]:
#Q4
import numpy as np

Aditya = np.linspace(10,100,25)
print("array:")
print(Aditya)
print("Dimensions: ", Aditya.ndim)
print("Shape: ", Aditya.shape)
print("Total Elements: ", Aditya.size)
print("Data type: ", Aditya.dtype)
print("Total bytes: ", Aditya.nbytes)

transpose = Aditya.reshape(1,-1)
print("transpose: ")
print(transpose)

print("transpose using T:")
print(Aditya.T)

array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions:  1
Shape:  (25,)
Total Elements:  25
Data type:  float64
Total bytes:  200
transpose: 
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
#Q5
import numpy as np
ucs420_Aditya = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])

print("original array:")
print(ucs420_Aditya)

print("Mean: ", np.mean(ucs420_Aditya))

print("Median:", np.median(ucs420_Aditya))

print("Maximum:", np.max(ucs420_Aditya))

print("Minimum:", np.min(ucs420_Aditya))

print("Unique elements:", np.unique(ucs420_Aditya))

reshaped_ucs420_Aditya = ucs420_Aditya.reshape(4, 3)

print("Reshaped Array (4 x 3):")
print(reshaped_ucs420_Aditya)

# Resize into 2 rows and 3 columns
resized_ucs420_Aditya = np.resize(ucs420_Aditya, (2, 3))

print("Resized Array (2 x 3):")
print(resized_ucs420_Aditya)


original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean:  43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
