In [ ]:
#Q1
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

#a)
corrected_temperature = temperature + 2
print("a) Corrected temperatures:", corrected_temperature)

#b)
fahrenheit = (9 / 5) * temperature + 32
print("b) Temperatures in Fahrenheit:", fahrenheit)

#c)
readings_greater_32 = temperature[temperature > 32]
print("c) Readings greater than 32°C:", readings_greater_32)

#d)
count = np.sum(temperature > 32)
print("d) Count:", count)

#e)
print("e)")
print("Vectorization : Performs operations on the entire NumPy array at once, avoiding explicit for loops and generally improving performance.")
print("Boolean indexing: Uses a condition such as temperature > 32 to select only the required elements, making filtering concise and efficient.")


a) Corrected temperatures: [27 30 33 37 40 29 35 42]
b) Temperatures in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
c) Readings greater than 32°C: [35 38 33 40]
d) Count: 4
e)
Vectorization : Performs operations on the entire NumPy array at once, avoiding explicit for loops and generally improving performance.
Boolean indexing: Uses a condition such as temperature > 32 to select only the required elements, making filtering concise and efficient.


In [ ]:
#Q2
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

#a)
print("a) Total steps:", np.sum(steps))

#b)
print("b) Mean steps:", np.mean(steps))

#c)
print("c)")
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))

#d)
print("d) Total per day:", np.sum(steps, axis=0))

#e)
print("e) Total per user:", np.sum(steps, axis=1))

#f)
position = np.unravel_index(np.argmax(steps), steps.shape)
print("f) Maximum position:", position)

a) Total steps: 84200
b) Mean steps: 7016.666666666667
c)
Maximum: 9500
Minimum: 4500
d) Total per day: [26500 27300 30400]
e) Total per user: [18300 24500 14400 27000]
f) Maximum position: (np.int64(3), np.int64(2))


In [ ]:
#Q3
import numpy as np

#a)
original = np.array([1, 2, 3, 4, 5, 6])

#b)
subset = original[1:4]

#c)
subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

#d)
copied = original[1:4].copy()
copied[0] = 500
print("d)")
print("Original after modifying copied:", original)
print("Copied array:", copied)

#e)
matrix = np.arange(1, 13).reshape(3, 4)
print("e)")
print("3 x 4 matrix:\n", matrix)

#f)
print("f)")
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:\n", matrix[1:3, 2:4])

#g)
flat_array = matrix.flatten()
ravel_array = matrix.ravel()
print("g)")
print("Flatten:", flat_array)
print("Ravel:", ravel_array)

#h)
ravel_array[0] = 100
print("h)")
print("Matrix after modifying ravel:", matrix)

#i)
flat_array[1] = 200
print("i)")
print("Matrix after modifying flatten:", matrix)

#j)
print("j)")
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4]
d)
Original after modifying copied: [  1 999   3   4   5   6]
Copied array: [500   3   4]
e)
3 x 4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f)
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
 [[ 7  8]
 [11 12]]
g)
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
h)
Matrix after modifying ravel: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
i)
Matrix after modifying flatten: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
j)
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [ ]:
#Q4
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
], dtype=float)

y = np.array([40, 65, 30, 85], dtype=float)

#a)
print("a)")
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

#b)
print("b)")
print("Transpose of X:\n", X.T)

#c)
XTX = X.T @ X
print("c)")
print("X.T @ X:\n", XTX)

#d)
XTX_inv = np.linalg.inv(XTX)
print("d)")
print("Inverse of X.T @ X:\n", XTX_inv)

#e)
beta = XTX_inv @ X.T @ y
print("e)")
print("Regression coefficients:", beta)

#g)
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("g)")
print("Predicted assistance score:", predicted_score)

a)
Shape of X: (4, 3)
Dimensions of X: 2
b)
Transpose of X:
 [[ 6.  5.  8.  4.]
 [70. 50. 80. 30.]
 [ 3.  6.  2.  8.]]
c)
X.T @ X:
 [[  141.  1430.    96.]
 [ 1430. 14700.   910.]
 [   96.   910.   113.]]
d)
Inverse of X.T @ X:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
e)
Regression coefficients: [-0.15921454  0.14083853 10.06302242]
g)
Predicted assistance score: 75.27862544779117
